"use client"

import GameCard from "./game-card"

const GAMES = [
  {
    id: 1,
    slug: "tic-tac-toe",
    name: "Poop-Tac-Toe",
    description: "Tic-Tac-Toe",
    lore: "Three swirls in a row to flush victory.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "3 in a row",
    image: "/images/angry-poop.png",
    playerCount: 2,
  },
  {
    id: 2,
    slug: "checkers",
    name: "Checker Diarrhea",
    description: "Checkers",
    lore: "Your pieces get flushed one by one.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "Capture all pieces",
    image: "/images/neon-woman-1.png",
    playerCount: 2,
  },
  {
    id: 3,
    slug: "gomoku",
    name: "Gomoku Sludge",
    description: "Gomoku",
    lore: "Get five in a row before the swamp fills.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "5 in a row",
    image: "/images/neon-woman-2.png",
    playerCount: 2,
  },
  {
    id: 4,
    slug: "dots-and-boxes",
    name: "Dots & Feces",
    description: "Dots & Boxes",
    lore: "Draw lines. Own shit. Lose everything.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "Most boxes",
    image: "/images/forbidden-tag.png",
    playerCount: 2,
  },
  {
    id: 5,
    slug: "halma",
    name: "Halma Hell",
    description: "Halma",
    lore: "Race across the sewer. Someone always drowns.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "Reach opposite corner",
    image: "/images/sewer-lounge.png",
    playerCount: 2,
  },
  {
    id: 6,
    slug: "nine-mens-morris",
    name: "Nine Shit Morris",
    description: "Nine Men's Morris",
    lore: "Mill your opponent or get milled.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "Three in a mill",
    image: "/images/datxit-after-dark.png",
    playerCount: 2,
  },
  {
    id: 7,
    slug: "bubble-shooter",
    name: "Bubble Flush",
    description: "Bubble Shooter",
    lore: "Pop bubbles before they overflow the bowl.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "Clear all bubbles",
    image: "/images/placeholder.svg?height=300&width=400&query=bubble%20game",
    playerCount: 2,
  },
  {
    id: 8,
    slug: "chess",
    name: "Royal Flush",
    description: "Chess",
    lore: "Crown and king battle across the throne.",
    betRange: "0.02–0.15 $DATX",
    winCondition: "Checkmate opponent",
    image: "/images/placeholder.svg?height=300&width=400&query=chess%20game",
    playerCount: 2,
  },
  {
    id: 9,
    slug: "backgammon",
    name: "Backgammon Bluff",
    description: "Backgammon",
    lore: "Race your pieces home before they drown.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "Bear off all pieces",
    image: "/images/placeholder.svg?height=300&width=400&query=backgammon",
    playerCount: 2,
  },
  {
    id: 10,
    slug: "dominoes",
    name: "Domino Drain",
    description: "Dominoes",
    lore: "Match tiles. Chain reactions cost you.",
    betRange: "0.01–0.08 $DATX",
    winCondition: "Empty your hand",
    image: "/images/placeholder.svg?height=300&width=400&query=dominoes",
    playerCount: 2,
  },
  {
    id: 11,
    slug: "peg-solitaire",
    name: "Peg Plunge",
    description: "Peg Solitaire",
    lore: "Eliminate pegs until one remains. Or sink.",
    betRange: "0.01–0.08 $DATX",
    winCondition: "One peg left",
    image: "/images/placeholder.svg?height=300&width=400&query=peg%20solitaire",
    playerCount: 1,
  },
  {
    id: 12,
    slug: "battleship",
    name: "Battle Breach",
    description: "Battleship",
    lore: "Sink enemy vessels in the sewer depths.",
    betRange: "0.02–0.15 $DATX",
    winCondition: "Sink all ships",
    image: "/images/placeholder.svg?height=300&width=400&query=battleship%20game",
    playerCount: 2,
  },
  {
    id: 13,
    slug: "ludo",
    name: "Ludo Leak",
    description: "Ludo",
    lore: "Roll dice. Rush home. Or drown trying.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "Reach home first",
    image: "/images/placeholder.svg?height=300&width=400&query=ludo%20board%20game",
    playerCount: 2,
  },
  {
    id: 14,
    slug: "go",
    name: "Go with the Flow",
    description: "Go",
    lore: "Territory control in the ancient sewer.",
    betRange: "0.02–0.15 $DATX",
    winCondition: "Control most territory",
    image: "/images/placeholder.svg?height=300&width=400&query=go%20game",
    playerCount: 2,
  },
  {
    id: 15,
    slug: "scrabble",
    name: "Scrabble Sludge",
    description: "Scrabble",
    lore: "Spell words. Lose points. Spiral down.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "Highest score",
    image: "/images/placeholder.svg?height=300&width=400&query=scrabble%20board",
    playerCount: 2,
  },
  {
    id: 16,
    slug: "ticket-to-ride",
    name: "Transit Trench",
    description: "Ticket to Ride",
    lore: "Build routes through the underground network.",
    betRange: "0.02–0.15 $DATX",
    winCondition: "Complete longest route",
    image: "/images/placeholder.svg?height=300&width=400&query=ticket%20to%20ride",
    playerCount: 3,
  },
  {
    id: 17,
    slug: "risk",
    name: "Risk the Rats",
    description: "Risk",
    lore: "Conquer territories. Lose armies. Burn cash.",
    betRange: "0.02–0.2 $DATX",
    winCondition: "Control all territories",
    image: "/images/placeholder.svg?height=300&width=400&query=risk%20board%20game",
    playerCount: 3,
  },
  {
    id: 18,
    slug: "poker",
    name: "Poker Pit",
    description: "Poker",
    lore: "All-in in the sewers. No folding now.",
    betRange: "0.05–0.25 $DATX",
    winCondition: "Best hand wins",
    image: "/images/placeholder.svg?height=300&width=400&query=poker%20cards",
    playerCount: 2,
  },
  {
    id: 19,
    slug: "rummy",
    name: "Rummy Rush",
    description: "Rummy",
    lore: "Meld cards faster than your opponent.",
    betRange: "0.01–0.1 $DATX",
    winCondition: "Meld all cards",
    image: "/images/placeholder.svg?height=300&width=400&query=rummy%20cards",
    playerCount: 2,
  },
  {
    id: 20,
    slug: "uno",
    name: "Uno Underground",
    description: "Uno",
    lore: "One card left. One chance. One flush.",
    betRange: "0.01–0.08 $DATX",
    winCondition: "Empty your hand",
    image: "/images/placeholder.svg?height=300&width=400&query=uno%20card%20game",
    playerCount: 2,
  },
]

export default function GameGrid() {
  return (
    <section className="relative z-10 py-12 px-6">
      <div className="max-w-6xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {GAMES.map((game) => (
            <GameCard key={game.id} game={game} />
          ))}
        </div>
      </div>
    </section>
  )
}
